# This is a basic workflow to help you get started with Actions

name: CI

## trigger workflows
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  branch_protection_rule:
    types: [deleted]

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  build:
    defaults:
      run:
        shell: bash
        working-directory: ./scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Ls at root
        run: ls -lh
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install
        working-directory: .
  

