# This is a basic workflow to help you get started with Actions

name: CI

# workflow level
env:
  server: production

## trigger workflows
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  branch_protection_rule:
    types: [deleted]

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  build:
    env:
      server: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - env:
          server: development
        run: echo "estou deployando no servidor = $server"
      - name: criando environment variable
        run: echo "environment_variable_compartilhada_do_step_anterior=igor" >> "$GITHUB_ENV"
      - name: printando environment variable
        run: echo $environment_variable_compartilhada_do_step_anterior
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm run build

  install:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm install
      - name: Install dependencies
        run: npm install
  

