# This is a basic workflow to help you get started with Actions

name: CI

# workflow level
env:
  server: production

## trigger workflows
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  branch_protection_rule:
    types: [deleted]

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  build:
    outputs:
      build-output: ${{ steps.set-output.outputs.environment_variable_compartilhada_do_job_anterior }}
    env:
      server: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - env:
          server: development
        run: echo "estou deployando no servidor = $server"
      - name: acessando secret
        env: 
          secret: ${{ secrets.MY_SUPER_SECRET }}
        run: echo $secret
      - name: criando environment variable
        run: echo "environment_variable_compartilhada_do_step_anterior=igor" >> "$GITHUB_ENV"
      - name: printando environment variable
        run: echo $environment_variable_compartilhada_do_step_anterior
      - name: criando environment variable para o proximo job
        run: echo "environment_variable_compartilhada_do_job_anterior=igor_job" >> "$GITHUB_OUTPUT"
        id: set-output
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm run build
      - name: criando arquivo test.txt
        run: echo "testando" > test.txt
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: upload_test_txt
          path: test.txt
  install:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm install
      - name: Install dependencies
        run: npm install
      - name: printando variavel do job anterior
        run: echo ${{ needs.build.outputs.build-output }}
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: upload_test_txt
      - name: print conteudo do arquivo teste.txt
        run: cat test.txt
      

  

