# This is a basic workflow to help you get started with Actions

name: CI

## trigger workflows
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  branch_protection_rule:
    types: [deleted]

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  random_print:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        env:
          LEVEL: ${{ inputs.logLevel }}
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo $LEVEL 
  

